language: objective-c
osx_image: xcode7.3
xcode_workspace: aerogear-otp.ios.xcworkspace
xcode_scheme: aerogear-otp.ios
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
